source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'mysql2', '< 0.3'
gem 'jquery-rails', '>= 1.0.3'
gem 'haml-rails'
gem 'rspec-rails'
gem 'rake', '0.8.7'
gem 'json'
gem 'rest-graph'
gem 'rest-client'
