require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FriendsController do

  # This should return the minimal set of attributes required to create a valid
  # Friend. As you add validations to Friend, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all friends as @friends" do
      friend = Friend.create! valid_attributes
      get :index
      assigns(:friends).should eq([friend])
    end
  end

  describe "GET show" do
    it "assigns the requested friend as @friend" do
      friend = Friend.create! valid_attributes
      get :show, :id => friend.id.to_s
      assigns(:friend).should eq(friend)
    end
  end

  describe "GET new" do
    it "assigns a new friend as @friend" do
      get :new
      assigns(:friend).should be_a_new(Friend)
    end
  end

  describe "GET edit" do
    it "assigns the requested friend as @friend" do
      friend = Friend.create! valid_attributes
      get :edit, :id => friend.id.to_s
      assigns(:friend).should eq(friend)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Friend" do
        expect {
          post :create, :friend => valid_attributes
        }.to change(Friend, :count).by(1)
      end

      it "assigns a newly created friend as @friend" do
        post :create, :friend => valid_attributes
        assigns(:friend).should be_a(Friend)
        assigns(:friend).should be_persisted
      end

      it "redirects to the created friend" do
        post :create, :friend => valid_attributes
        response.should redirect_to(Friend.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved friend as @friend" do
        # Trigger the behavior that occurs when invalid params are submitted
        Friend.any_instance.stub(:save).and_return(false)
        post :create, :friend => {}
        assigns(:friend).should be_a_new(Friend)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Friend.any_instance.stub(:save).and_return(false)
        post :create, :friend => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested friend" do
        friend = Friend.create! valid_attributes
        # Assuming there are no other friends in the database, this
        # specifies that the Friend created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Friend.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => friend.id, :friend => {'these' => 'params'}
      end

      it "assigns the requested friend as @friend" do
        friend = Friend.create! valid_attributes
        put :update, :id => friend.id, :friend => valid_attributes
        assigns(:friend).should eq(friend)
      end

      it "redirects to the friend" do
        friend = Friend.create! valid_attributes
        put :update, :id => friend.id, :friend => valid_attributes
        response.should redirect_to(friend)
      end
    end

    describe "with invalid params" do
      it "assigns the friend as @friend" do
        friend = Friend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Friend.any_instance.stub(:save).and_return(false)
        put :update, :id => friend.id.to_s, :friend => {}
        assigns(:friend).should eq(friend)
      end

      it "re-renders the 'edit' template" do
        friend = Friend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Friend.any_instance.stub(:save).and_return(false)
        put :update, :id => friend.id.to_s, :friend => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested friend" do
      friend = Friend.create! valid_attributes
      expect {
        delete :destroy, :id => friend.id.to_s
      }.to change(Friend, :count).by(-1)
    end

    it "redirects to the friends list" do
      friend = Friend.create! valid_attributes
      delete :destroy, :id => friend.id.to_s
      response.should redirect_to(friends_url)
    end
  end

end
